admin: SDR7XY33FYTDJTRF2CAXU5VGQWIQU4YOGZYPMYZ7ZAZTDGINQYMRJWZC

horizon: http://localhost:8000/

creators: ["SAN4NLOGBGWHNJADLOSWT4GBYKMP7ZMGE74NLMHHRFXL6PB45HVWLX3W", "SAMEBGASYZEAJZLTKMWFUE47ZMPNIP34WNHAEYN5TVF7DZQW3242XHKM", "SC4JZ3ML5KCJFY43L5YONXWUETHF6WNMCGQGM4VTP7G3SH6HEWCWWBQJ"]

payers:
  SAN4NLOGBGWHNJADLOSWT4GBYKMP7ZMGE74NLMHHRFXL6PB45HVWLX3W: SAMEBGASYZEAJZLTKMWFUE47ZMPNIP34WNHAEYN5TVF7DZQW3242XHKM