admin: SDR7XY33FYTDJTRF2CAXU5VGQWIQU4YOGZYPMYZ7ZAZTDGINQYMRJWZC

passphrase: Stellar Load Test Network

horizon: http://host.docker.internal:8000/

creators: ["SAN4NLOGBGWHNJADLOSWT4GBYKMP7ZMGE74NLMHHRFXL6PB45HVWLX3W", "SAMEBGASYZEAJZLTKMWFUE47ZMPNIP34WNHAEYN5TVF7DZQW3242XHKM", "SC4JZ3ML5KCJFY43L5YONXWUETHF6WNMCGQGM4VTP7G3SH6HEWCWWBQJ"]

payers:
  SCQJXD46Y2SSTYIUO6XMFUXL6UAQAACDLU75QPAIH7XRWLJGQKTXG2KT: SB2RJMYSGQVYJ42TKJZK6HNF3O6ULJV5Y4I2TRGQO5SE2MRKESBI77YG
  SBQLTUKFCNJPVQOKYX5LAGIXIOOHT62V5I3MKFNA3MA4UXPWZTTJKYCD: SCJNF47C6WZ52NOMBNZ6SGHGGXWDCRIUXXOUWNWBKZLLBHHO47SO73JC

amount: 10

duration: 600000